export default {
  SetWalletConnected: {
    SET_WALLET_CONNECTED_SUCCESS: "SET_WALLET_CONNECTED_SUCCESS",
  },
  SetWalletDisconnected: {
    SET_WALLET_DISCONNECTED_SUCCESS: "SET_WALLET_DISCONNECTED_SUCCESS",
  },
  SetProvider: {
    SET_PROVIDER_SUCCESS: "SET_PROVIDER_SUCCESS",
  },
  SetContracts: {
    SET_CONTRACTS_REQUEST: "SET_CONTRACTS_REQUEST",
    SET_CONTRACTS_SUCCESS: "SET_CONTRACTS_SUCCESS",
    SET_CONTRACTS_FAIL: "SET_CONTRACTS_FAIL",
    SET_CONTRACTS_PENDING: "SET_CONTRACTS_PENDING",
  },
  SetWalletAddress: {
    SET_WALLET_ADDRESS_SUCCESS: "SET_WALLET_ADDRESS_SUCCESS",
  },
  SetBalances: {
    SET_BALANCES_REQUEST: "SET_BALANCES_REQUEST",
    SET_BALANCES_SUCCESS: "SET_BALANCES_SUCCESS",
    SET_BALANCES_FAIL: "SET_BALANCES_FAIL",
    SET_BALANCES_PENDING: "SET_BALANCES_PENDING",
  },
  GetDidVote:{
    GET_DID_VOTE_REQUEST: "GET_DID_VOTE_REQUEST",
    GET_DID_VOTE_SUCCESS: "GET_DID_VOTE_SUCCESS",
    GET_DID_VOTE_FAIL: "GET_DID_VOTE_FAIL",
    GET_DID_VOTE_PENDING: "GET_DID_VOTE_PENDING",
  },
  GetProposalVotes:{
    GET_PROPOSAL_VOTES_REQUEST: "GET_PROPOSAL_VOTES_REQUEST",
    GET_PROPOSAL_VOTES_SUCCESS: "GET_PROPOSAL_VOTES_SUCCESS",
    GET_PROPOSAL_VOTES_FAIL: "GET_PROPOSAL_VOTES_FAIL",
    GET_PROPOSAL_VOTES_PENDING: "GET_PROPOSAL_VOTES_PENDING",
  },
  GetProposalData:{
    GET_PROPOSAL_DATA_REQUEST: "GET_PROPOSAL_DATA_REQUEST",
    GET_PROPOSAL_DATA_SUCCESS: "GET_PROPOSAL_DATA_SUCCESS",
    GET_PROPOSAL_DATA_FAIL: "GET_PROPOSAL_DATA_FAIL",
    GET_PROPOSAL_DATA_PENDING: "GET_PROPOSAL_DATA_PENDING",
  },
  GetProposalStatus:{
    GET_PROPOSAL_STATUS_REQUEST: "GET_PROPOSAL_STATUS_REQUEST",
    GET_PROPOSAL_STATUS_SUCCESS: "GET_PROPOSAL_STATUS_SUCCESS",
    GET_PROPOSAL_STATUS_FAIL: "GET_PROPOSAL_STATUS_FAIL",
    GET_PROPOSAL_STATUS_PENDING: "GET_PROPOSAL_STATUS_PENDING",
  },
  GetProposalResult:{
    GET_PROPOSAL_RESULT_REQUEST: "GET_PROPOSAL_RESULT_REQUEST",
    GET_PROPOSAL_RESULT_SUCCESS: "GET_PROPOSAL_RESULT_SUCCESS",
    GET_PROPOSAL_RESULT_FAIL: "GET_PROPOSAL_RESULT_FAIL",
    GET_PROPOSAL_RESULT_PENDING: "GET_PROPOSAL_RESULT_PENDING",
  },
  GetMinVotesNeeded:{
    GET_PROPOSAL_MIN_VOTES_REQUEST: "GET_PROPOSAL_MIN_VOTES_REQUEST",
    GET_PROPOSAL_MIN_VOTES_SUCCESS: "GET_PROPOSAL_MIN_VOTES_SUCCESS",
    GET_PROPOSAL_MIN_VOTES_FAIL: "GET_PROPOSAL_MIN_VOTES_FAIL",
    GET_PROPOSAL_MIN_VOTES_PENDING: "GET_PROPOSAL_MIN_VOTES_PENDING",
  },
  Vote:{
    PROPOSAL_VOTE_REQUEST: "PROPOSAL_VOTE_REQUEST",
    PROPOSAL_VOTE_SUCCESS: "PROPOSAL_VOTE_SUCCESS",
    PROPOSAL_VOTE_FAIL: "PROPOSAL_VOTE_FAIL",
    PROPOSAL_VOTE_PENDING: "PROPOSAL_VOTE_PENDING",
  },
  Stake:{
    STAKE_TOKENS_REQUEST:"STAKE_TOKENS_REQUEST",
    STAKE_TOKENS_SUCCESS:"STAKE_TOKENS_SUCCESS",
    STAKE_TOKENS_FAIL:"STAKE_TOKENS_FAIL",
    STAKE_TOKENS_PENDING:"STAKE_TOKENS_PENDING",
  },
  Withdraw:{
    WITHDRAW_TOKEN_REQUEST:"WITHDRAW_TOKEN_REQUEST",
    WITHDRAW_TOKEN_SUCCESS:"WITHDRAW_TOKEN_SUCCESS",
    WITHDRAW_TOKEN_FAIL:"WITHDRAW_TOKEN_FAIL",
    WITHDRAW_TOKEN_PENDING:"WITHDRAW_TOKEN_PENDING",

  },
  CreateProposal:{
    CREATE_PROPOSAL_PENDING:"CREATE_PROPOSAL_PENDING",
    CREATE_PROPOSAL_REQUEST:"CREATE_PROPOSAL_REQUEST",
    CREATE_PROPOSAL_FAIL:"CREATE_PROPOSAL_FAIL",
    CREATE_PROPOSAL_SUCCESS:"CREATE_PROPOSAL_SUCCESS"
  },
  ApproveTokens:{
    APPROVE_TOKENS_REQUEST:"APPROVE_TOKENS_REQUEST",
    APPROVE_TOKENS_SUCCESS:"APPROVE_TOKENS_SUCCESS",
    APPROVE_TOKENS_FAIL:"APPROVE_TOKENS_FAIL",
    APPROVE_TOKENS_PENDING:"APPROVE_TOKENS_PENDING",
  },
  StakedBalance:{
    GET_STAKED_BALANCE_PENDING:"GET_STAKED_BALANCE_PENDING",
    GET_STAKED_BALANCE_REQUEST:"GET_STAKED_BALANCE_REQUEST",
    GET_STAKED_BALANCE_FAIL:"GET_STAKED_BALANCE_FAIL",
    GET_STAKED_BALANCE_SUCCESS:"GET_STAKED_BALANCE_SUCCESS"
  },
  ProposalStatus:{
    GET_PROPOSAL_STATUS_PENDING:"GET_PROPOSAL_STATUS_PENDING",
    GET_PROPOSAL_STATUS_REQUEST:"GET_PROPOSAL_STATUS_REQUEST",
    GET_PROPOSAL_STATUS_FAIL:"GET_PROPOSAL_STATUS_FAIL",
    GET_PROPOSAL_STATUS_SUCCESS:"GET_PROPOSAL_STATUS_SUCCESS"
  },
  ProposalData:{
    GET_PROPOSAL_DATA_PENDING:"GET_PROPOSAL_DATA_PENDING",
    GET_PROPOSAL_DATA_REQUEST:"GET_PROPOSAL_DATA_REQUEST",
    GET_PROPOSAL_DATA_FAIL:"GET_PROPOSAL_DATA_FAIL",
    GET_PROPOSAL_DATA_SUCCESS:"GET_PROPOSAL_DATA_SUCCESS"
  },
  ProposalVotes:{
    GET_PROPOSAL_VOTES_PENDING:"GET_PROPOSAL_VOTES_PENDING",
    GET_PROPOSAL_VOTES_REQUEST:"GET_PROPOSAL_VOTES_REQUEST",
    GET_PROPOSAL_VOTES_FAIL:"GET_PROPOSAL_VOTES_FAIL",
    GET_PROPOSAL_VOTES_SUCCESS:"GET_PROPOSAL_VOTES_SUCCESS"
  },
  ProposalResult:{
    GET_PROPOSAL_RESULT_PENDING:"GET_PROPOSAL_RESULT_PENDING",
    GET_PROPOSAL_RESULT_REQUEST:"GET_PROPOSAL_RESULT_REQUEST",
    GET_PROPOSAL_RESULT_FAIL:"GET_PROPOSAL_RESULT_FAIL",
    GET_PROPOSAL_RESULT_SUCCESS:"GET_PROPOSAL_RESULT_SUCCESS"
  },
  ProposalNumber:{
    GET_PROPOSAL_NUMBER_PENDING:"GET_PROPOSAL_NUMBER_PENDING",
    GET_PROPOSAL_NUMBER_REQUEST:"GET_PROPOSAL_NUMBER_REQUEST",
    GET_PROPOSAL_NUMBER_FAIL:"GET_PROPOSAL_NUMBER_FAIL",
    GET_PROPOSAL_NUMBER_SUCCESS:"GET_PROPOSAL_NUMBER_SUCCESS"
  },
  GetAllProposals:{
    GET_ALL_PROPOSAL_DATA_PENDING:"GET_ALL_PROPOSAL_DATA_PENDING",
    GET_ALL_PROPOSAL_DATA_REQUEST:"GET_ALL_PROPOSAL_DATA_REQUEST",
    GET_ALL_PROPOSAL_DATA_FAIL:"GET_ALL_PROPOSAL_DATA_FAIL",
    GET_ALL_PROPOSAL_DATA_SUCCESS:"GET_ALL_PROPOSAL_DATA_SUCCESS"
  },
  GetUnlockTime:{
    GET_UNLOCK_TIME_PENDING:"GET_UNLOCK_TIME_PENDING",
    GET_UNLOCK_TIME_REQUEST:"GET_UNLOCK_TIME_REQUEST",
    GET_UNLOCK_TIME_FAIL:"GET_UNLOCK_TIME_FAIL",
    GET_UNLOCK_TIME_SUCCESS:"GET_UNLOCK_TIME_SUCCESS"
  },
};
